# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy secrets if they do not already exist in the key vault
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs these variables:
#   appName = 'xxx-kv-demo' (makes the resources globally unique - replace xxx with your initials or an organization acronym)
#   subscriptionName = '<yourSubscriptionName>' (where the resource group will be deployed)
#   location = 'eastus' (or whatever location you want the resource group deployed to)
#   keyVaultOwnerUserId = '<yourUserAccountGuid>' (will grant you access to read the key vault - can be left blank)
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
# ----------------------------------------------------------------------------------------------------
trigger:
  - none

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runResourceDeploy
    displayName: Run Resource Deploy
    type: boolean
    default: true
  - name: runSecretDeploy
    displayName: Run Secret Deploy
    type: boolean
    default: true

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-only-pipe.yml
  parameters:
    runResourceDeploy: ${{ parameters.runResourceDeploy }}
    resourceTemplateFolderName: 'infra'
    resourceTemplateFileName: 'main-create-resources.bicep'
    runSecretDeploy: ${{ parameters.runSecretDeploy }}
    secretTemplateFolderName: '3-Create_If_Not_Exists/Bicep'
    secretTemplateFileName: 'main-secrets-exists.bicep'
